kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: uet-local
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/16"
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "control-plane-role=true"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "worker-role=true"
  extraPortMappings:
  - containerPort: 80     # Kong Proxy
    hostPort: 80
  - containerPort: 443    # Kong Proxy HTTPS
    hostPort: 443
- role: worker
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "worker-role=true"
  extraPortMappings:
  - containerPort: 80     # Kong Proxy
    hostPort: 80
  - containerPort: 443    # Kong Proxy HTTPS
    hostPort: 443